### PR TITLE
Add HeaderTemplate parameter

### LINKED ISSUE #49: Header templates
Nyaamaste.

It would be great if the library could support a header template as well as a footer template. The header could be used to add a "Add product" or similar button or a checkbox to toggle a filter. The footer could be used for paging and showing the number of returned rows.

Thank you !

### PR DESCRIPTION
**Pull request by natsuo**
Adds a HeaderTemplate parameter to the component. 

The header can be used for adding a missing record (product, customer, issue) or even filter existing records. If the ResultTemplate has multiple columns it can also be used to show column names.

The footer can still be used to display things like number of records or pagination links.

Fixes #49

### CODE REVIEW

**Comment by vertonghenb** [comment]
@natsuo Looks great, do you mind adding a small gif of the final product so we can see the changes you did?
ScreenToGif can be very helpfull to do so.

**Comment by natsuo** [comment]
Certainly.

I updated the client application, but I'll throw in a gif. Do you want me to update the project's screenshot or just put it in this PR ?

**Comment by natsuo** [comment]
header

**Comment by chrissainty** [comment]
Hi @natsuo, yes I think it's worth updating the project screenshot with the new gif.

**Comment by natsuo** [comment]
I'll set up a better example header and footer template to better show off the feature then. Also need to update the README.md. Sorry about the delay Chris, I didn't get notified about your comment.

**Comment by natsuo** [comment]
I've stumbled upon some show stopping issues with the current implementation of the Typeahead.

* The header and footer aren't clickable. If there are elements in there, like a checkbox or button/link, the Typeahead component will close instead of letting the user interact with the element.
* The header and footer should be outside the scrollable area, as in always visible if the template has been set.
* The other content on the page is affected by the results-view (dropdown). That causes the Submit button and other content to shift up and down depending on the state and size of the results view. This can be observed in the .gif I posted yesterday.

Features also required:
* How can I problematically tell the component to do another query from a method triggered by checkbox, button or other control inside the header/footer
* I should be able to tell the Typeahead component if I want the results view to stay open or disappear upon clicking on a control inside the header or footer.

**Comment by chrissainty** [comment]
@natsuo Apologies for this, my head has been all over the place the last few weeks preparing for a conference I'm speaking at tomorrow.

The issues you've raised above are valid but most are fixed in the vnext branch, which is the next major release for the control. I know this is a real pain but would you mind creating a PR to that branch instead? I completely understand if you don't and I apologise for not pointing this out earlier.

**Comment by natsuo** [comment]
I'll add the neccessary changes on the current v4.1.0.

**Pull request closed without merging**
