### PR TITLE
Adding CssClasses from the EditContext to the inputfield Fixes #58

### LINKED ISSUE #58: Add CssClassses from EditContext.FieldCssClass to input
Much like InputBase in AspNetCore ([here](https://github.com/aspnet/AspNetCore/blob/8c02467b4a218df3b1b0a69bceb50f5b64f482b1/src/Components/Web/src/Forms/InputBase.cs#L146)) the status classes from the EditContext should be added to the input. This is needed so that we can style the input itself when it is valid, invalid and modified.

### PR DESCRIPTION
**Pull request by magahl**
This PR adds FieldCssClasses to the `<input/>`

### CODE REVIEW

**Comment by chrissainty** [comment]
Thanks for creating this PR @magahl. I don't think the input is the right place to put the CSS classes. As the control swaps the input in and out of view depending on if you're searching or not. Applying the styles to just the input would mean they would disappear in certain scenarios.

I would suggest putting the CSS classes on the top level div so they are present at all times.

**Comment by magahl** [comment]
You are correct @chrissainty. This also makes the `invalid` class from the css file come into play and make the input have a red border.

**Comment by chrissainty** [comment]
@magahl I hope you don't mind but as I was just finishing some other fixes I've just included your changes into my other PR. So I'm going to close this one now. Thank you for the contribution.

**Comment by magahl** [comment]
No problem. I just need the fix :)

**Comment by chrissainty** [comment]
Just pushed to NuGet. You should be able to update in the next half hour :)

**Pull request closed without merging**
